# Boilerplate code generated by OVITO Pro 3.3.5
from ovito.io import *
from ovito.data import *
from ovito.modifiers import *
from ovito.pipeline import *
import numpy
import sys

from os.path import exists

print ("start")

if exists("dump.phase"):
    #output_file = str(sys.argv[2])
    dump_file = str("dump.phase")

    # Data import:
    pipeline = import_file(dump_file, multiple_frames = True, columns = ["Particle Identifier", "Particle Type", "Position.X", "Position.Y", "Position.Z"])

    print ("imported")

    # Expression selection:
    pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType==2'))

    # Delete selected:
    pipeline.modifiers.append(DeleteSelectedModifier())

    # All Uranium atoms
    pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType==1'))

    # Common Neighbor Analysis:
    pipeline.modifiers.append(CommonNeighborAnalysisModifier())

    # Expression selection:
    pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'StructureType==1'))


    #pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'fin_lat==1'))


    data = pipeline.compute(1)

    print(data.attributes["ExpressionSelection.count.2"])

    all_atoms = data.attributes["ExpressionSelection.count.2"]
    atoms_solid_state = data.attributes["ExpressionSelection.count.3"]
    percent = atoms_solid_state/all_atoms
    file1 = open('melting_count.temp', 'w')
    file1.write(str(percent))
    file1.close()
else:
    file1 = open('melting_count.temp', 'w')
    file1.write(str(0.0))
    file1.close()
	